### ISSUE TITLE
Missing indication of maximum file size

### ISSUE THREAD

**Issue by kabel** [unl/UNL_MediaHub#253]
The upload form is missing information that lets the user know what the maximum file size is for the system/server.

**Comment by mfairchild365** [comment]
It looks like this was fixed here: https://github.com/unl/UNL_MediaHub/commit/2a0fbb857892afb6a705290ddda2f4f3630fb171

However, it would be better to set the upload size dynamically as per the server configuration, so I will leave this open for now.
