### ISSUE TITLE
Captions search is showing webVTT elements like '<v>'

### ISSUE THREAD

**Issue by mfairchild365** [unl/UNL_MediaHub#271]
For example, take a look at: http://mediahub.unl.edu/media/4588

The first line contains `<v ->`...

I think this can be fixed by avoiding the use of the `track.cues[0].text` property and instead using `text` property.

For example, run the following in the console on the page:
```
WDN.jQuery('video.wdn_player')[0].textTracks[0].cues[0].getCueAsHTML()
```
vs
```
WDN.jQuery('video.wdn_player')[0].textTracks[0].cues[0].text
```

Although, I'm not really sure how to get it to work with our embed code. We appear to be referencing `track.entries.text[i]` instead of track.cues[0]` (which I don't think exists and I'm not sure why). It might require some browser testing.

**Comment by mfairchild365** [comment]
@spennythug Can you look into this while I'm gone next week?

**Comment by mfairchild365** [comment]
Actually, I went ahead and put a band-aid on it with this commit: https://github.com/unl/UNL_MediaHub/commit/07072389b6acdcf14d99c823de49f7130b8bfa9b

Basically stripping out any html tags and leaving just text, which is what we might want anyway.

Thoughts @spennythug and @kabel ?

**Comment by kabel** [comment]
Good enough for now, I think.
