### ISSUE TITLE
Include links to meida in feeds

### ISSUE THREAD

**Issue by mfairchild365** [unl/UNL_MediaHub#315]
Currently, only the url to the .mp4 is included in feeds, which makes it difficult to create the embed code dynamically.

Feeds should probably include:

1. A link to the iframe
2. A link to the media's page

> I'd like to request a tweak and/or addition to the RSS that Mediahub channels currently output. Long explanation incoming, sorry.
  
> The WDN embed code for videos has changed, of course, to an iframe that uses the page url instead of the direct link to the .mp4 file, right? 
  
> However, the RSS feeds generated for Mediahub channels only output the direct URL to the .mp4, not the page URL that is now used in the embed code. It would be really really really really great if this was consistent across the board. Can we make a change to Mediahub so there's a field for the page, and not just the direct link to the .mp4? 

> (for example) We're using a Feeds Importer in UNLcms to import videos from the RSS feed for the “Humanities on the Edge” channel https://mediahub.unl.edu/channels/637?format=xml

**Comment by kabel** [comment]
Sounds reasonable to me. Just make sure we don't break the podcast format https://support.google.com/googleplay/podcasts/answer/6260341.

1. We might have to create a new element in the mediahub namespace schema https://mediahub.unl.edu/schema/mediahub.xsd to accommodate this customization
2. The existing `<link>` element might be a good candidate for the main URL
