### ISSUE TITLE
Improve share widget

### ISSUE THREAD

**Issue by mfairchild365** [unl/UNL_MediaHub#320]
The share widget needs some love, especially for mobile. Specific issues:
1. Not all options are shown at mobile width (list is too long)
2. get a go url doesn't work correctly (it navigates the iframe to a different page). This can be easily fixed by setting the target for the link, but a more fluid UI would be better (ajax submit to api and return the URL)

Perhaps the share widget should open as a modal rather than a dropdown?

**Comment by jsturek** [comment]
out of date
