### ISSUE TITLE
media:content url isn't correct

### ISSUE THREAD

**Issue by ericras** [unl/UNL_MediaHub#449]
https://github.com/unl/UNL_MediaHub/blob/master/src/UNL/MediaHub/Media.php#L224

For example: https://mediahub.unl.edu/media/17080?format=xml

That file doesn't exist: https://mediahub.unl.edu/uploads/f7e20fa01be74b8b92c2065c83fa5ba9.mp4
 
(Oddly enough, it did exist as "5ede638d22c0f9326703eeb66e0d27dd.mp4" and has since been deleted as part of the transcoding garbage cleanup.)

**Comment by tommyneu** [comment]
This looks to be fixed, closing the issue
